-- List all shows with at least one genre

SELECT TV_SHOWS.TITLE, TV_SHOW_GENRES.GENRE_ID
FROM TV_SHOWS
JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
ORDER BY TV_SHOWS.TITLE ASC, TV_SHOW_GENRES.GENRE_ID ASC;

