-- List all genres for the show Dexter

SELECT GENRES.NAME
FROM TV_SHOWS
JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
JOIN GENRES ON TV_SHOW_GENRES.GENRE_ID = GENRES.ID
WHERE TV_SHOWS.TITLE = 'Dexter'
ORDER BY GENRES.NAME ASC;

