-- List all Comedy shows

SELECT TV_SHOWS.TITLE
FROM TV_SHOWS
JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
JOIN GENRES ON TV_SHOW_GENRES.GENRE_ID = GENRES.ID
WHERE GENRES.NAME = 'Comedy'
ORDER BY TV_SHOWS.TITLE ASC;

