-- List all shows with their genres, show NULL if no genre

SELECT TV_SHOWS.TITLE, GENRES.NAME
FROM TV_SHOWS
LEFT JOIN TV_SHOW_GENRES ON TV_SHOWS.ID = TV_SHOW_GENRES.SHOW_ID
LEFT JOIN GENRES ON TV_SHOW_GENRES.GENRE_ID = GENRES.ID
ORDER BY TV_SHOWS.TITLE ASC, GENRES.NAME ASC;

